
DROP TABLE entities;
DROP TABLE items;
DROP TABLE transactions;
DROP TABLE transaction_entries;
DROP TABLE locations;
DROP TABLE entities_entered_location;

-- data done
CREATE TABLE entities (
	name VARCHAR(64) PRIMARY KEY NOT NULL,
	type VARCHAR(64) NOT NULL -- player, npc, mob, chest, marketplace, boss
);

CREATE TABLE items (
	id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	name VARCHAR(256) NOT NULL,
	weight FLOAT NOT NULL,
	description VARCHAR(1024),
	category VARCHAR(32) NOT NULL,
	base_price DECIMAL(11,2),
	custom_params JSON
);

CREATE TABLE transactions (
	id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	stamp TIMESTAMP NOT NULL,
	owner_a VARCHAR(64), --- references entities.name
	owner_b VARCHAR(64), --- references entities.name
	
	CONSTRAINT owner_a_ref
		FOREIGN KEY (owner_a)
		REFERENCES entities (name),
	CONSTRAINT owner_b_ref
		FOREIGN KEY (owner_b)
		REFERENCES entities (name)
);

CREATE TABLE transaction_entries (
	id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	transaction INT NOT NULL, -- references transactions.id
	amount INT NOT NULL,
	item INT NOT NULL, -- references items.id
	from_a char check (from_a in (0,1)),
	
	CONSTRAINT transaction_ref
		FOREIGN KEY (transaction)
		REFERENCES transactions (id),
	CONSTRAINT item_ref
		FOREIGN KEY (item)
		REFERENCES items (id)
);

-- data done
CREATE TABLE locations (
	name VARCHAR(128) NOT NULL PRIMARY KEY,
	players_limit INT NOT NULL,
	max_players_noted_at_once_with_no_lags INT,
	max_players_noted_at_once_with_no_lags_date DATE
);

-- data done
CREATE TABLE entities_entered_location (
	id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	name VARCHAR(64) NOT NULL, -- references entities.name
	location VARCHAR(128) NOT NULL, -- references locations.name
	date_time TIMESTAMP,
	
	CONSTRAINT location_ref
		FOREIGN KEY (location)
		REFERENCES locations (name),
	CONSTRAINT entity_ref
		FOREIGN KEY (name)
		REFERENCES entities (name)
);




-- data done
CREATE TABLE entity_types (
	type VARCHAR(64) PRIMARY KEY NOT NULL -- player, npc, mob, chest, marketplace, boss
);

CREATE TABLE item_categories (
	type VARCHAR(32) PRIMARY KEY NOT NULL
);

