
-- done
CREATE TABLE entities (
	name VARCHAR(64) PRIMARY KEY NOT NULL,
	type VARCHAR(64) NOT NULL -- player, npc, mob, chest, marketplace, boss
);

CREATE TABLE items (
	id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	name VARCHAR(256) NOT NULL,
	weight FLOAT NOT NULL,
	description VARCHAR(1024),
	category VARCHAR(32) NOT NULL,
	base_price DECIMAL(11,2),
	custom_params JSON
);

CREATE TABLE transactions (
	id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	stamp TIMESTAMP NOT NULL,
	owner_a VARCHAR(64), --- references entities.name
	owner_b VARCHAR(64) --- references entities.name
);

CREATE TABLE transaction_entries (
	id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	transaction INT NOT NULL, -- references transactions.id
	amount INT NOT NULL,
	item INT NOT NULL, -- references items.id
	from_a char check (from_a in (0,1))
);

-- done
CREATE TABLE locations (
	name VARCHAR(128) NOT NULL PRIMARY KEY,
	players_limit INT NOT NULL,
	max_players_noted_at_once_with_no_lags INT,
	max_players_noted_at_once_with_no_lags_date DATE
);

CREATE TABLE entities_entered_location (
	id INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	name VARCHAR(64) NOT NULL, -- references entities.name
	location VARCHAR(128) NOT NULL, -- references locations.name
	date_time TIMESTAMP
);




-- done
CREATE TABLE entity_types (
	type VARCHAR(64) PRIMARY KEY NOT NULL -- player, npc, mob, chest, marketplace, boss
);

